name: learn-to-code
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - pytest-flake8
  - pytest-mypy
  - pytest-cov
  - pytest
  - black
  - isort
  - mypy
  - pre-commit
  - python==3.9
  - flake8
  - pytest-mock
  - scvi-tools
  - scanpy
  - python-igraph
  - leidenalg
  - urllib3